# Lab 2: numpy

#### Practice Exercise 1

Create the following NumPy arrays: 
1. A 1-D array called zeros having 10 elements and all the elements are set to zero. 
2. A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’. 
3. A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int. 
4. Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data: 2.7,  0,  -2,  3.4,  10.6,  0,  -19 99.9 13 
5. A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float


In [48]:
# Write your answer here

import numpy as np

#Q1:
zeros = np.zeros(10, dtype=int)
zeros

#Q2:
vowels = np.array(['a','e','o','u','i'])
vowels

#Q3:
ones = np.ones(10, dtype=int).reshape(2,5)
ones

#Q4:
myarray1 = np.array([[2.7, 0, -2],[3.4, 10.6, 0],[-19, 99.9, 13]])
myarray1

#Q5:
myarray2 = np.arange(4,4+15*4,4, dtype=float).reshape(3,5)
myarray2

array([[ 4.,  8., 12., 16., 20.],
       [24., 28., 32., 36., 40.],
       [44., 48., 52., 56., 60.]])

Using the arrays created in Question above, write NumPy commands for the following: 
1. Find the dimensions, shape, size, data type of the items and itemsize of arrays zeros, vowels, ones, myarray1 and myarray2. 
2. Reshape the array ones to have all the 10 elements in a single row. 
3. Display the 2nd and 3rd element of the array vowels. 
4. Display all elements in the 2nd and 3rd row of the array myarray1. 
5. Display the elements in the 1st and 2nd column of the array myarray1. 
6. Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1. 
7. Reverse the array of vowels.

In [84]:
#Write your answer here

#Q1:
zeros.ndim, zeros.shape, zeros.size, zeros.dtype.type, zeros.itemsize
vowels.ndim, vowels.shape, vowels.size, vowels.dtype.type, vowels.itemsize
ones.ndim, ones.shape, ones.size, ones.dtype.type, ones.itemsize
myarray1.ndim, myarray1.shape, myarray1.size, myarray1.dtype.type, myarray1.itemsize
myarray2.ndim, myarray2.shape, myarray2.size, myarray2.dtype.type, myarray2.itemsize

#Q2:
ones = ones.reshape(1,10)
ones

#Q3:
vowels[1:3]

#Q4:
myarray1[1:3 , : ]

#Q5:
myarray1[ : , 0:2 ]

#Q6:
myarray1[1:3 , 0:1 ] 

#Q7:
vowels[::-1]

array(['i', 'u', 'o', 'e', 'a'], dtype='<U1')

Using the arrays created in Question above, write NumPy commands for the following:
1. Divide all elements of array ones by 3. 
2. Add the arrays myarray1 and myarray2. 
3. Subtract myarray1 from myarray2 and store the result in a new array. 
4. Multiply myarray1 and myarray2 elementwise. 
5. Do the matrix multiplication of myarray1 and myarray2 and store the result in a new array myarray3. 
6. Divide myarray1 by myarray2. 
7. Find the cube of all elements of myarray1 and divide the resulting array by 2. 
8. Find the square root of all elements of myarray2   and divide the resulting array by 2. The result  should be rounded to two places of decimals.

In [194]:
# Write your answer here

#Q1:
ones/3

#Q2:
myarray1 + myarray2[ : , :3]

#Q3:
myarray3 = myarray1 + myarray2[ : , :3]
myarray3

#Q4:
myarray1 * myarray2[ : , :3]

#Q5:
myarray4 = np.dot(myarray1, myarray2)
myarray4

#Q6:
myarray1 / myarray2[ : , :3]

#Q7:
(myarray1 ** 3)/2

#Q8:
np.round(np.sqrt(myarray2)/2, 2)

array([[1.  , 1.41, 1.73, 2.  , 2.24],
       [2.45, 2.65, 2.83, 3.  , 3.16],
       [3.32, 3.46, 3.61, 3.74, 3.87]])

Using the arrays created above, write NumPy commands for the following: 
1. Find the transpose of ones and myarray2. 
2. Sort the array vowels in reverse. 
3. Sort the array myarray1 such that it brings the lowest value of the column in the first row and so on.

In [196]:
# Write your answer here

#Q1:
ones.T
myarray2.T

#Q2:
np.sort(vowels)[::-1]

#Q3:
np.sort(myarray2, axis=0)

array([[ 4.,  8., 12., 16., 20.],
       [24., 28., 32., 36., 40.],
       [44., 48., 52., 56., 60.]])

Create a 2-D array called myarray4 using arange() having 14 rows and 3 columns with start value = -1, step size 0.25 having. Split this array row wise into 3 equal parts and print the result. 

In [198]:
# Write your answer here

myarray4 = np.arange(-1, -1 + 0.25 * 42, 0.25).reshape(14,3)
np.array_split(myarray4, 3)

[array([[-1.  , -0.75, -0.5 ],
        [-0.25,  0.  ,  0.25],
        [ 0.5 ,  0.75,  1.  ],
        [ 1.25,  1.5 ,  1.75],
        [ 2.  ,  2.25,  2.5 ]]),
 array([[2.75, 3.  , 3.25],
        [3.5 , 3.75, 4.  ],
        [4.25, 4.5 , 4.75],
        [5.  , 5.25, 5.5 ],
        [5.75, 6.  , 6.25]]),
 array([[6.5 , 6.75, 7.  ],
        [7.25, 7.5 , 7.75],
        [8.  , 8.25, 8.5 ],
        [8.75, 9.  , 9.25]])]

Using the myarray4 created in the above questions, write commands for the following: 
1. Find the sum of all elements. 
2. Find the sum of all elements row wise
3. Find the sum of all elements column wise. 
4. Find the max of all elements. 
5. Find the min of all elements in each row. 
6. Find the mean of all elements in each row. 
7. Find the standard deviation column wise.

In [200]:
# Write your ansewr here

#Q1:
np.sum(myarray4)

#Q2:
np.sum(myarray4, axis=1)

#Q3:
np.sum(myarray4, axis=0)

#Q4:
np.max(myarray4)

#Q5:
np.min(myarray4, axis=1)

#Q6:
np.mean(myarray4, axis=1)

#Q7:
np.std(myarray4, axis=0)

array([3.02334666, 3.02334666, 3.02334666])

#### Practice Exercise 2
Read the coordinates of the capital cities of the world from the country-capital-lat-long-population.csv file. Use NumPy to print the name and coordinates of the capital city closest to the Saudi Arabia capital - Riyadh.

Note that:

1. The Country Name for Saudi Arabia is given as Saudi Arabia in the data.
2. The ‘closeness’ of capital cities from the Saudi Arabia capital is based on the Euclidean distance of their coordinates to those of the Saudi Arabia capital.


Hints:

1. Use read_html() from the Pandas library to read the table.
2. Use the to_numpy() function of the Pandas DataFrame class to convert a DataFrame to a Numpy array
3. Use broadcasting to compute the euclidean distance of capital cities from Riyadh.

In [54]:
# Write your answer here

import pandas as pd
import numpy as np

capitals = pd.read_csv('country-capital-lat-long-population.csv')
capitals.head()

capital_location = capitals.loc[:, ['Latitude', 'Longitude'] ].to_numpy()
KSA_location = capitals.loc [capitals.Country == 'Saudi Arabia', ['Latitude', 'Longitude']].to_numpy()
distance_from_riyadh = np.sqrt(np.sum((KSA_location - capital_location) ** 2, axis = 1))

distance_from_riyadh[distance_from_riyadh == 0] = 9999
closest_capital_index = np.argmin(distance_from_riyadh)

capitals.iloc[closest_capital_index,:]

Country                     Bahrain
Capital City    Al-Manamah (Manama)
Latitude                    26.2154
Longitude                   50.5832
Population                   564631
Capital Type                Capital
Name: 15, dtype: object

#### Practical Exercise 2

Use NumPy to:

1. Print the names of the countries of the top 10 capital cities closest to the US capital - Washington DC.

2. Create and print a NumPy array containing the coordinates of the top 10 cities.

In [52]:
# Write your answer here

import pandas as pd
import numpy as np

capitals = pd.read_csv('country-capital-lat-long-population.csv')

DC_location = capitals.loc[capitals['Capital City'] == 'Washington, D.C.', ['Latitude', 'Longitude']].to_numpy()

capital_locations = capitals.loc[:, ['Latitude', 'Longitude']].to_numpy()

distances = np.sqrt(np.sum((capital_locations - DC_location) ** 2, axis=1))

distances[distances == 0] = np.inf

closest_indices = np.argsort(distances)[:10]

closest_capitals = capitals.iloc[closest_indices]

print("Countries of the top 10 closest capital cities to Washington, DC:")
for country in closest_capitals['Country']:
    print(country)

top_10_coordinates = closest_capitals.loc[:, ['Latitude', 'Longitude']].to_numpy()
print("\nCoordinates of the top 10 closest capital cities to Washington, DC:")
print(top_10_coordinates)

Countries of the top 10 closest capital cities to Washington, DC:
Canada
Bahamas
Bermuda
Cuba
Turks and Caicos Islands
Cayman Islands
Haiti
Jamaica
Dominican Republic
Saint Pierre and Miquelon

Coordinates of the top 10 closest capital cities to Washington, DC:
[[ 45.4166 -75.698 ]
 [ 25.0582 -77.3431]
 [ 32.2915 -64.778 ]
 [ 23.1195 -82.3785]
 [ 21.4612 -71.1419]
 [ 19.2866 -81.3744]
 [ 18.5392 -72.335 ]
 [ 17.997  -76.7936]
 [ 18.4896 -69.9018]
 [ 46.7738 -56.1815]]
